services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: peluqueria-anita
    env_file: .env
    # monta tu código en /usr/src/app para recarga en caliente
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "10000:10000"
    # en desarrollo fuerza npm dev + artisan serve
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 10000 &
        php artisan serve --host=0.0.0.0 --port=10000
      "
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: peluqueria-db
    restart: always
    env_file: .env         # define allí DB_HOST, DB_USER, DB_PASS, DB_NAME
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
